### ISSUE TITLE
球球宁别误导人啦

### ISSUE THREAD

**Issue by shinshinran** [mougua/webp2gif#1]
这明明是别人写得png转gif的，不是webp，webp是另一种后缀

**Comment by mougua** [comment]
需要安装 libwebp-0.6.0 并将 webp 先转换成 png，所以代码里面有这么一行：
`os.system(r'D:\libwebp-0.6.0-windows-x86\bin\dwebp.exe D:\用户目录\我的图片\sticker.webp -o d:\mylab\lab\out.png')`

这只是我以前自用的东西，所以没多作解释。你这阴阳怪气的标题是怎么回事？显得自己低幼？
